export { default as Me } from './Me/Me.tsx'
export { default as Contact } from './Contact/Contact.tsx'
export { default as Experience } from './Experience/Experience.tsx'
export { default as Skills } from './Skills/Skills.tsx'
export { default as Projects } from './Projects/Projects.tsx'
export { default as Education } from './Education/Education.tsx'
export { default as Language } from './Language/Language.tsx'
